glslangvalidator -V debug.vert -o debug.vert.spv
glslangvalidator -V debug.frag -o debug.frag.spv
glslangvalidator -V mrt.vert -o mrt.vert.spv
glslangvalidator -V mrt.frag -o mrt.frag.spv
glslangvalidator -V shadow.vert -o shadow.vert.spv
glslangvalidator -V shadow.frag -o shadow.frag.spv
glslangvalidator -V deferred.vert -o deferred.vert.spv
glslangvalidator -V deferred.frag -o deferred.frag.spv
glslangvalidator -V ao_spawn_rays.comp -o ao_spawn_rays.comp.spv
glslangvalidator -V ao_resolve.comp -o ao_resolve.comp.spv
glslangvalidator -V biltateral_filter.comp -o biltateral_filter.comp.spv
glslangvalidator -V gi_sample_lights.comp -o gi_sample_lights.comp.spv
glslangvalidator -V gi_accumulate_samples.comp -o gi_accumulate_samples.comp.spv
glslangvalidator -V texture_repack.comp -o texture_repack.comp.spv
glslangvalidator -V debug_textures.vert -o debug_textures.vert.spv
glslangvalidator -V rt_clear.comp -o rt_clear.comp.spv
glslangvalidator -V gi_spawn_rays_from_gbuffer.comp -o gi_spawn_rays_from_gbuffer.comp.spv
glslangvalidator -V gi_spawn_rays_from_gbuffer_gloss.comp -o gi_spawn_rays_from_gbuffer_gloss.comp.spv
glslangvalidator -V di_spawn_rays.comp -o di_spawn_rays.comp.spv
glslangvalidator -V di_resolve.comp -o di_resolve.comp.spv
glslangvalidator -V cubemap_filter_sh9.comp -o cubemap_filter_sh9.comp.spv
glslangvalidator -V cubemap_sh9_project.comp -o cubemap_sh9_project.comp.spv
glslangvalidator -V cubemap_sh9_downsample.comp -o cubemap_sh9_downsample.comp.spv
glslangvalidator -V cubemap_sh9_final.comp -o cubemap_sh9_final.comp.spv
glslangvalidator -V cubemap_render.frag -o cubemap_render.frag.spv
glslangvalidator -V cubemap_render.vert -o cubemap_render.vert.spv
glslangvalidator -V cubemap_sky.frag -o cubemap_sky.frag.spv
glslangvalidator -V cubemap_sky.vert -o cubemap_sky.vert.spv
glslangvalidator -V edge_detection.frag -o edge_detection.frag.spv
glslangvalidator -V edge_detection.vert -o edge_detection.vert.spv
glslangvalidator -V weight_calc.frag -o weight_calc.frag.spv
glslangvalidator -V weight_calc.vert -o weight_calc.vert.spv
glslangvalidator -V mlaa_final_blend.frag -o mlaa_final_blend.frag.spv
glslangvalidator -V mlaa_final_blend.vert -o mlaa_final_blend.vert.spv
