glslangvalidator -V debug.vert -o debug.vert.spv
glslangvalidator -V debug.frag -o debug.frag.spv
glslangvalidator -V mrt.vert -o mrt.vert.spv
glslangvalidator -V mrt.frag -o mrt.frag.spv
glslangvalidator -V shadow.vert -o shadow.vert.spv
glslangvalidator -V shadow.frag -o shadow.frag.spv
glslangvalidator -V deferred.vert -o deferred.vert.spv
glslangvalidator -V deferred.frag -o deferred.frag.spv
glslangvalidator -V camera_rays.comp -o camera_rays.comp.spv
glslangvalidator -V ao.comp -o ao.comp.spv
glslangvalidator -V gi.comp -o gi.comp.spv
glslangvalidator -V ao_resolve.comp -o ao_resolve.comp.spv
glslangvalidator -V biltateral_filter.comp -o biltateral_filter.comp.spv
glslangvalidator -V gi_resolve.comp -o gi_resolve.comp.spv
glslangvalidator -V texture_repack.comp -o texture_repack.comp.spv
glslangvalidator -V debug_textures.vert -o debug_textures.vert.spv
glslangvalidator -V debug_textures.frag -o debug_textures.frag.spv